# Use an existing Docker image with Python pre-installed
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy all files and directories from the local directory to /app in the container
COPY . /app

# Copy the requirements.txt file into the container
COPY requirements.txt /app

# Install dbt and other dependencies from requirements.txt
RUN apt-get update -y && \
    apt-get install -y git && \
    pip install --upgrade pip && \
    pip install -r requirements.txt
    

# Copy the dbt project into the container
COPY dbt_dskola_sf/ /app/dbt_dskola_sf

# Set the working directory to the dbt project directory
WORKDIR /app/dbt_dskola_sf

# Set the environment variable to specify the profiles directory
ENV DBT_PROFILES_DIR=/app

# Define the command to run when the container starts
CMD ["dbt", "run"]
